"""Added hashkey and name to Chat table

Revision ID: 4fa96c65a469
Revises: e43b6b4728d6
Create Date: 2021-03-17 19:52:25.991672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa96c65a469'
down_revision = 'e43b6b4728d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('hash_key', sa.String(), nullable=True))
    op.add_column('chat', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.drop_column('chat', 'name')
    op.drop_column('chat', 'hash_key')
    # ### end Alembic commands ###
